env_name: Humanoid-v5
hidden_dim: 34
total_steps: 200000
buffer_size: 1000000
batch_size: 50
start_steps: 10000
updates_per_step: 1
lr: 0.0003
gamma: 0.99
tau: 0.005
alpha: 0.2
auto_tune_alpha: true
log_dir: runs/
seed: 42
# --- Arquitetura usada neste treino ---
activation: relu
normalize_obs: false
